### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by lrnselfreliance** [lrnselfreliance/wrolpi#11]
Downloading fails on a new system with this error:
```
api_1  | Traceback (most recent call last):
api_1  |   File "/opt/wrolpi/api/videos/downloader.py", line 116, in update_channels
api_1  |     update_channel(channel)
api_1  |   File "/opt/wrolpi/api/videos/downloader.py", line 59, in update_channel
api_1  |     channel['next_download'] = today() + timedelta(seconds=download_frequency)
api_1  | TypeError: unsupported type for timedelta seconds component: NoneType
```

**Comment by lrnselfreliance** [comment]
Fixed in a14970e2
