### ISSUE TITLE
Videos statistics fails when refresh isn't complete

### ISSUE THREAD

**Issue by lrnselfreliance** [lrnselfreliance/wrolpi#50]
When a Video refresh isn't yet complete, the statistics fails with:
```
Nov 02 18:47:44 ubuntu python[5551]: Traceback (most recent call last):
Nov 02 18:47:44 ubuntu python[5551]:   File "/opt/wrolpi/venv/lib/python3.8/site-packages/sanic/app.py", line 909, in handle_request
Nov 02 18:47:44 ubuntu python[5551]:     response = await response
Nov 02 18:47:44 ubuntu python[5551]:   File "/opt/wrolpi/wrolpi/schema.py", line 100, in wrapped
Nov 02 18:47:44 ubuntu python[5551]:     result = await result
Nov 02 18:47:44 ubuntu python[5551]:   File "/opt/wrolpi/modules/videos/api.py", line 159, in statistics
Nov 02 18:47:44 ubuntu python[5551]:     ret = await get_statistics()
Nov 02 18:47:44 ubuntu python[5551]:   File "/opt/wrolpi/modules/videos/lib.py", line 298, in get_statistics
Nov 02 18:47:44 ubuntu python[5551]:     historical_stats['average_size'] = (sum(i['size'] for i in monthly_videos) // len(monthly_videos)) \
Nov 02 18:47:44 ubuntu python[5551]: TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by lrnselfreliance** [comment]
This could be fixed by simply returning an error when statistics is requested.  An error like "Refresh your videos to view statistics." should be displayed to the user.

**Comment by StruckCroissant** [comment]
I'll take this one
