### ISSUE TITLE
YT-DLP reports error with .cache

### ISSUE THREAD

**Issue by lrnselfreliance** [lrnselfreliance/wrolpi#96]
Downloading a video reports this error.  Modify yt-dlp download params to use `--no-cache-dir` to disable caching.
```
api_1      | [2022-02-07 19:24:00,131] [modules.videos.downloader.youtube-dl] [WARNING] Writing cache to '/.cache/yt-dlp/youtube-nsig/0cd11746.json' failed: Traceback (most recent call last):
api_1      |   File "/usr/local/lib/python3.8/site-packages/yt_dlp/cache.py", line 49, in store
api_1      |     os.makedirs(os.path.dirname(fn))
api_1      |   File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
api_1      |     makedirs(head, exist_ok=exist_ok)
api_1      |   File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
api_1      |     makedirs(head, exist_ok=exist_ok)
api_1      |   File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
api_1      |     mkdir(name, mode)
api_1      | PermissionError: [Errno 13] Permission denied: '/.cache'
```

**Comment by lrnselfreliance** [comment]
Fixed in c772b57ddbc36dbde947cc5f2560e5c91fb4bf48
